name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual runs

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # Enable Git LFS support

      # Step 2: Install Git LFS
      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull

      # Step 3: Push to Hugging Face Hub
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git fetch https://Lucas-F:$HF_TOKEN@huggingface.co/spaces/Lucas-F/cat-dog-classify main
          git push https://Lucas-F:$HF_TOKEN@huggingface.co/spaces/Lucas-F/cat-dog-classify main --force
